import torch
# This script is adapted from the following repository: https://github.com/ermongroup/ddim


def data_transform(X):
    return 2 * X - 1.0


def inverse_data_transform(X):
    return torch.clamp((X + 1.0) / 2.0, 0.0, 1.0)

def data_transform_depth(X):
    # min_val = torch.min(X)
    # max_val = torch.max(X)
    # return 2.0 * (X - min_val) / (max_val - min_val) - 1.0

    d2 = torch.quantile(X, 0.02)
    d98 = torch.quantile(X, 0.98)
    # d̃ = ((d - d2) / (d98 - d2) - 0.5) × 2
    normalized = ((X - d2) / (d98 - d2) - 0.5) * 2.0
    
    return normalized

def data_transform_depth_inverse(Y_normalized, d2, d98):
    """
    Inversely transforms a normalized depth map (range [-1, 1]) back to its original depth scale.

    Args:
        Y_normalized (torch.Tensor): The depth map generated by the diffusion model, 
            with values in the range [-1, 1].
        d2 (float or torch.Tensor): The 2nd percentile of the original depth map 
            calculated during the preprocessing stage.
        d98 (float or torch.Tensor): The 98th percentile of the original depth map 
            calculated during the preprocessing stage.

    Returns:
        torch.Tensor: The depth map restored to its original scale.
    """
    
    reconstruction = ((Y_normalized / 2.0) + 0.5) * (d98 - d2) + d2
    
    return reconstruction

def relu_transform(X):
    return torch.clamp(X, min=0.0)